import type { CustomCardType } from "@/lib/custom-card-types";
import { findCustomCardType, stereotypeLabel } from "@/lib/custom-card-types";
import type { ElementType, StormElement } from "@/types/storm-element";

export interface ElementStyle {
  label: string;
  shortLabel: string;
  bg: string;
  border: string;
  text: string;
  /** Pastel hex for inline styles (palette / canvas). */
  fill: string;
  stroke: string;
  ink: string;
  defaultWidth: number;
  defaultHeight: number;
  shape: "rounded" | "rectangle" | "pill" | "wide";
  rotation?: number;
}

/** Soft post-it pastels — shared by palette buttons and canvas stickies. */
export const ELEMENT_STYLES: Record<ElementType, ElementStyle> = {
  domainEvent: {
    label: "Domain Event",
    shortLabel: "Event",
    bg: "bg-orange-100",
    border: "border-orange-300",
    text: "text-orange-950",
    fill: "#ffedd5",
    stroke: "#fdba74",
    ink: "#7c2d12",
    defaultWidth: 160,
    defaultHeight: 72,
    shape: "rounded",
  },
  command: {
    label: "Command",
    shortLabel: "Cmd",
    bg: "bg-blue-100",
    border: "border-blue-300",
    text: "text-blue-950",
    fill: "#dbeafe",
    stroke: "#93c5fd",
    ink: "#1e3a8a",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rounded",
  },
  actor: {
    label: "Actor",
    shortLabel: "Actor",
    bg: "bg-yellow-100",
    border: "border-yellow-300",
    text: "text-yellow-950",
    fill: "#fef9c3",
    stroke: "#fcd34d",
    ink: "#713f12",
    defaultWidth: 110,
    defaultHeight: 48,
    shape: "pill",
  },
  aggregate: {
    label: "Aggregate",
    shortLabel: "Agg",
    bg: "bg-yellow-100",
    border: "border-yellow-400",
    text: "text-yellow-950",
    fill: "#fef08a",
    stroke: "#eab308",
    ink: "#713f12",
    defaultWidth: 280,
    defaultHeight: 200,
    shape: "rectangle",
  },
  policy: {
    label: "Policy",
    shortLabel: "Policy",
    bg: "bg-fuchsia-100",
    border: "border-fuchsia-300",
    text: "text-fuchsia-950",
    fill: "#fae8ff",
    stroke: "#e879f9",
    ink: "#6b21a8",
    defaultWidth: 170,
    defaultHeight: 72,
    shape: "rounded",
  },
  readModel: {
    label: "Read Model",
    shortLabel: "Read",
    bg: "bg-emerald-100",
    border: "border-emerald-300",
    text: "text-emerald-950",
    fill: "#dcfce7",
    stroke: "#86efac",
    ink: "#064e3b",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rounded",
  },
  externalSystem: {
    label: "External System",
    shortLabel: "Ext",
    bg: "bg-pink-100",
    border: "border-pink-300",
    text: "text-pink-950",
    fill: "#fce7f3",
    stroke: "#f9a8d4",
    ink: "#9d174d",
    defaultWidth: 160,
    defaultHeight: 72,
    shape: "rectangle",
  },
  ui: {
    label: "UI",
    shortLabel: "UI",
    bg: "bg-slate-100",
    border: "border-slate-300",
    text: "text-slate-800",
    fill: "#f1f5f9",
    stroke: "#cbd5e1",
    ink: "#0f172a",
    defaultWidth: 130,
    defaultHeight: 60,
    shape: "rounded",
  },
  note: {
    label: "Notiz",
    shortLabel: "Notiz",
    bg: "bg-stone-50",
    border: "border-stone-300",
    text: "text-stone-800",
    fill: "#faf6ef",
    stroke: "#d6d0c4",
    ink: "#44403c",
    defaultWidth: 160,
    defaultHeight: 100,
    shape: "rounded",
  },
  instruction: {
    label: "Instruction",
    shortLabel: "Instr.",
    bg: "bg-teal-50",
    border: "border-teal-300",
    text: "text-teal-950",
    fill: "#f0fdfa",
    stroke: "#5eead4",
    ink: "#134e4a",
    defaultWidth: 176,
    defaultHeight: 112,
    shape: "rounded",
  },
  hotspot: {
    label: "Hotspot",
    shortLabel: "Hot",
    bg: "bg-red-100",
    border: "border-red-300",
    text: "text-red-950",
    fill: "#fee2e2",
    stroke: "#fca5a5",
    ink: "#7f1d1d",
    defaultWidth: 120,
    defaultHeight: 120,
    shape: "rectangle",
    rotation: 45,
  },
  link: {
    label: "Link",
    shortLabel: "Link",
    bg: "bg-sky-50",
    border: "border-sky-300",
    text: "text-sky-950",
    fill: "#eef8ff",
    stroke: "#38bdf8",
    ink: "#0c4a6e",
    defaultWidth: 168,
    defaultHeight: 48,
    shape: "rounded",
  },
  pivotalEvent: {
    label: "Pivotal Event",
    shortLabel: "Pivotal",
    bg: "bg-amber-100",
    border: "border-amber-300",
    text: "text-amber-950",
    fill: "#fef3c7",
    stroke: "#fcd34d",
    ink: "#7c2d12",
    defaultWidth: 280,
    defaultHeight: 48,
    shape: "wide",
  },
  entity: {
    label: "Entity",
    shortLabel: "Entity",
    bg: "bg-teal-100",
    border: "border-teal-300",
    text: "text-teal-950",
    fill: "#ccfbf1",
    stroke: "#5eead4",
    ink: "#134e4a",
    defaultWidth: 150,
    defaultHeight: 72,
    shape: "rounded",
  },
  valueObject: {
    label: "Value Object",
    shortLabel: "VO",
    bg: "bg-cyan-100",
    border: "border-cyan-300",
    text: "text-cyan-950",
    fill: "#cffafe",
    stroke: "#67e8f9",
    ink: "#164e63",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  domainService: {
    label: "Domain Service",
    shortLabel: "Service",
    bg: "bg-indigo-100",
    border: "border-indigo-300",
    text: "text-indigo-950",
    fill: "#e0e7ff",
    stroke: "#a5b4fc",
    ink: "#312e81",
    defaultWidth: 170,
    defaultHeight: 72,
    shape: "rounded",
  },
  repository: {
    label: "Repository",
    shortLabel: "Repo",
    bg: "bg-stone-100",
    border: "border-stone-400",
    text: "text-stone-900",
    fill: "#e7e5e4",
    stroke: "#a8a29e",
    ink: "#1c1917",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rectangle",
  },
  factory: {
    label: "Factory",
    shortLabel: "Factory",
    bg: "bg-lime-100",
    border: "border-lime-300",
    text: "text-lime-950",
    fill: "#ecfccb",
    stroke: "#bef264",
    ink: "#365314",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  subdomain: {
    label: "Subdomain",
    shortLabel: "Sub",
    bg: "bg-violet-100",
    border: "border-violet-300",
    text: "text-violet-950",
    fill: "#ede9fe",
    stroke: "#a78bfa",
    ink: "#4c1d95",
    defaultWidth: 320,
    defaultHeight: 240,
    shape: "rectangle",
  },
  rule: {
    label: "Rule",
    shortLabel: "Rule",
    bg: "bg-amber-100",
    border: "border-amber-400",
    text: "text-amber-950",
    fill: "#fde68a",
    stroke: "#fbbf24",
    ink: "#78350f",
    defaultWidth: 180,
    defaultHeight: 80,
    shape: "rounded",
  },
  example: {
    label: "Example",
    shortLabel: "Ex",
    bg: "bg-green-100",
    border: "border-green-300",
    text: "text-green-950",
    fill: "#bbf7d0",
    stroke: "#86efac",
    ink: "#14532d",
    defaultWidth: 170,
    defaultHeight: 90,
    shape: "rounded",
  },
  question: {
    label: "Question",
    shortLabel: "?",
    bg: "bg-sky-100",
    border: "border-sky-300",
    text: "text-sky-950",
    fill: "#bae6fd",
    stroke: "#7dd3fc",
    ink: "#0c4a6e",
    defaultWidth: 140,
    defaultHeight: 72,
    shape: "rounded",
  },
  activity: {
    label: "Activity",
    shortLabel: "Act",
    bg: "bg-blue-100",
    border: "border-blue-400",
    text: "text-blue-950",
    fill: "#bfdbfe",
    stroke: "#60a5fa",
    ink: "#1e3a8a",
    defaultWidth: 160,
    defaultHeight: 56,
    shape: "wide",
  },
  userTask: {
    label: "User Task",
    shortLabel: "Task",
    bg: "bg-sky-50",
    border: "border-sky-200",
    text: "text-sky-900",
    fill: "#e0f2fe",
    stroke: "#7dd3fc",
    ink: "#0c4a6e",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  userStory: {
    label: "User Story",
    shortLabel: "Story",
    bg: "bg-yellow-50",
    border: "border-yellow-300",
    text: "text-yellow-950",
    fill: "#fef9c3",
    stroke: "#fde047",
    ink: "#713f12",
    defaultWidth: 160,
    defaultHeight: 88,
    shape: "rounded",
  },
  release: {
    label: "Release",
    shortLabel: "Rel",
    bg: "bg-rose-100",
    border: "border-rose-300",
    text: "text-rose-950",
    fill: "#fecdd3",
    stroke: "#fda4af",
    ink: "#881337",
    defaultWidth: 320,
    defaultHeight: 40,
    shape: "wide",
  },
  slice: {
    label: "Slice",
    shortLabel: "Slice",
    bg: "bg-orange-50",
    border: "border-orange-300",
    text: "text-orange-950",
    fill: "#ffedd5",
    stroke: "#fdba74",
    ink: "#7c2d12",
    defaultWidth: 220,
    defaultHeight: 48,
    shape: "wide",
  },
  processStart: {
    label: "Start",
    shortLabel: "Start",
    bg: "bg-emerald-100",
    border: "border-emerald-400",
    text: "text-emerald-950",
    fill: "#d1fae5",
    stroke: "#34d399",
    ink: "#064e3b",
    defaultWidth: 88,
    defaultHeight: 88,
    shape: "pill",
  },
  processEnd: {
    label: "Ende",
    shortLabel: "Ende",
    bg: "bg-slate-200",
    border: "border-slate-500",
    text: "text-slate-900",
    fill: "#e2e8f0",
    stroke: "#64748b",
    ink: "#0f172a",
    defaultWidth: 88,
    defaultHeight: 88,
    shape: "pill",
  },
  processActivity: {
    label: "Aktivität",
    shortLabel: "Schritt",
    bg: "bg-blue-100",
    border: "border-blue-300",
    text: "text-blue-950",
    fill: "#dbeafe",
    stroke: "#93c5fd",
    ink: "#1e3a8a",
    defaultWidth: 170,
    defaultHeight: 80,
    shape: "rounded",
  },
  processGateway: {
    label: "Gateway",
    shortLabel: "GW",
    bg: "bg-amber-100",
    border: "border-amber-400",
    text: "text-amber-950",
    fill: "#fef3c7",
    stroke: "#fbbf24",
    ink: "#78350f",
    defaultWidth: 100,
    defaultHeight: 100,
    shape: "rectangle",
  },
  dataEntity: {
    label: "Entität",
    shortLabel: "Entity",
    bg: "bg-cyan-100",
    border: "border-cyan-400",
    text: "text-cyan-950",
    fill: "#cffafe",
    stroke: "#22d3ee",
    ink: "#164e63",
    defaultWidth: 180,
    defaultHeight: 100,
    shape: "rectangle",
  },
  dataAssociation: {
    label: "Assoziation",
    shortLabel: "Assoz.",
    bg: "bg-violet-100",
    border: "border-violet-300",
    text: "text-violet-950",
    fill: "#ede9fe",
    stroke: "#c4b5fd",
    ink: "#4c1d95",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  /** C4 Person — green actor (Context diagram). @see https://c4model.com/diagrams */
  c4Person: {
    label: "Person",
    shortLabel: "Person",
    bg: "bg-emerald-100",
    border: "border-emerald-600",
    text: "text-emerald-950",
    fill: "#d1fae5",
    stroke: "#059669",
    ink: "#064e3b",
    defaultWidth: 140,
    defaultHeight: 72,
    shape: "pill",
  },
  /** C4 Software System — blue box (Level 1, black-box). */
  c4SoftwareSystem: {
    label: "Software-System",
    shortLabel: "System",
    bg: "bg-blue-200",
    border: "border-blue-700",
    text: "text-blue-950",
    fill: "#bfdbfe",
    stroke: "#1d4ed8",
    ink: "#1e3a8a",
    defaultWidth: 220,
    defaultHeight: 100,
    shape: "rectangle",
  },
  /** C4 Container — deployable unit inside a system (Level 2). */
  c4Container: {
    label: "Container",
    shortLabel: "Container",
    bg: "bg-sky-100",
    border: "border-sky-600",
    text: "text-sky-950",
    fill: "#e0f2fe",
    stroke: "#0284c7",
    ink: "#0c4a6e",
    defaultWidth: 200,
    defaultHeight: 100,
    shape: "rectangle",
  },
  /** C4 Component — module inside a container (Level 3). */
  c4Component: {
    label: "C4 Komponente",
    shortLabel: "Komponente",
    bg: "bg-sky-50",
    border: "border-sky-400",
    text: "text-sky-950",
    fill: "#f0f9ff",
    stroke: "#38bdf8",
    ink: "#0c4a6e",
    defaultWidth: 170,
    defaultHeight: 84,
    shape: "rounded",
  },
  /** arc42 Blackbox — closed building block (like a C4 system from outside). */
  archBlackbox: {
    label: "Blackbox",
    shortLabel: "Blackbox",
    bg: "bg-blue-200",
    border: "border-blue-700",
    text: "text-blue-950",
    fill: "#bfdbfe",
    stroke: "#1d4ed8",
    ink: "#1e3a8a",
    defaultWidth: 200,
    defaultHeight: 110,
    shape: "rectangle",
  },
  /**
   * arc42 Whitebox / C4 scope boundary after zoom-in (dashed box around
   * containers or components — same role as the dashed system/container frame).
   */
  archWhitebox: {
    label: "Whitebox",
    shortLabel: "Whitebox",
    bg: "bg-slate-50",
    border: "border-slate-400",
    text: "text-slate-800",
    fill: "#f8fafc",
    stroke: "#64748b",
    ink: "#1e293b",
    defaultWidth: 320,
    defaultHeight: 220,
    shape: "rectangle",
  },
  /** Building-block leaf inside a Whitebox (maps to C4 Component level). */
  archComponent: {
    label: "Komponente",
    shortLabel: "Komponente",
    bg: "bg-sky-50",
    border: "border-sky-400",
    text: "text-sky-950",
    fill: "#f0f9ff",
    stroke: "#38bdf8",
    ink: "#0c4a6e",
    defaultWidth: 160,
    defaultHeight: 80,
    shape: "rounded",
  },
  /** Cloud Account / Landing Zone / Tenant boundary — drillable scope. */
  cloudBoundary: {
    label: "Cloud-Grenze",
    shortLabel: "Grenze",
    bg: "bg-slate-100",
    border: "border-slate-500",
    text: "text-slate-900",
    fill: "#f1f5f9",
    stroke: "#64748b",
    ink: "#0f172a",
    defaultWidth: 280,
    defaultHeight: 160,
    shape: "rectangle",
  },
  /** Network / VPC / subnet conceptually. */
  cloudNetwork: {
    label: "Netzwerk",
    shortLabel: "Netz",
    bg: "bg-teal-100",
    border: "border-teal-500",
    text: "text-teal-950",
    fill: "#ccfbf1",
    stroke: "#14b8a6",
    ink: "#134e4a",
    defaultWidth: 180,
    defaultHeight: 80,
    shape: "rounded",
  },
  /** Compute: VM, container, function, app service. */
  cloudCompute: {
    label: "Compute",
    shortLabel: "Compute",
    bg: "bg-sky-100",
    border: "border-sky-500",
    text: "text-sky-950",
    fill: "#e0f2fe",
    stroke: "#0ea5e9",
    ink: "#0c4a6e",
    defaultWidth: 170,
    defaultHeight: 80,
    shape: "rounded",
  },
  /** Data store: DB, object storage, cache, warehouse. */
  cloudDataStore: {
    label: "Datenspeicher",
    shortLabel: "Daten",
    bg: "bg-amber-100",
    border: "border-amber-500",
    text: "text-amber-950",
    fill: "#fef3c7",
    stroke: "#f59e0b",
    ink: "#78350f",
    defaultWidth: 170,
    defaultHeight: 80,
    shape: "rounded",
  },
  /** Messaging: queue, bus, stream, pub/sub. */
  cloudMessaging: {
    label: "Messaging",
    shortLabel: "Msg",
    bg: "bg-emerald-100",
    border: "border-emerald-500",
    text: "text-emerald-950",
    fill: "#d1fae5",
    stroke: "#10b981",
    ink: "#064e3b",
    defaultWidth: 160,
    defaultHeight: 72,
    shape: "rounded",
  },
  /** Identity / IAM / directory / secrets. */
  cloudIdentity: {
    label: "Identity",
    shortLabel: "IAM",
    bg: "bg-rose-100",
    border: "border-rose-400",
    text: "text-rose-950",
    fill: "#ffe4e6",
    stroke: "#fb7185",
    ink: "#881337",
    defaultWidth: 150,
    defaultHeight: 72,
    shape: "rounded",
  },
  /** Edge: CDN, API gateway, WAF, load balancer. */
  cloudEdge: {
    label: "Edge / Gateway",
    shortLabel: "Edge",
    bg: "bg-cyan-100",
    border: "border-cyan-500",
    text: "text-cyan-950",
    fill: "#cffafe",
    stroke: "#06b6d4",
    ink: "#164e63",
    defaultWidth: 170,
    defaultHeight: 72,
    shape: "rounded",
  },
  /** Managed / SaaS / PaaS catch-all. */
  cloudManagedService: {
    label: "Managed Service",
    shortLabel: "Managed",
    bg: "bg-stone-100",
    border: "border-stone-400",
    text: "text-stone-900",
    fill: "#f5f5f4",
    stroke: "#a8a29e",
    ink: "#292524",
    defaultWidth: 180,
    defaultHeight: 80,
    shape: "rounded",
  },
  customCard: {
    label: "Kartentyp",
    shortLabel: "Typ",
    bg: "bg-slate-100",
    border: "border-slate-300",
    text: "text-slate-900",
    fill: "#f1f5f9",
    stroke: "#94a3b8",
    ink: "#0f172a",
    defaultWidth: 160,
    defaultHeight: 80,
    shape: "rounded",
  },
};

/** True when `type` has a palette/canvas style (imported JSON may carry unknown types). */
export function isKnownElementType(type: unknown): type is ElementType {
  return typeof type === "string" && Object.prototype.hasOwnProperty.call(ELEMENT_STYLES, type);
}

/** Style lookup that never returns undefined — unknown types fall back to note. */
export function styleForElementType(type: unknown): ElementStyle {
  if (isKnownElementType(type)) return ELEMENT_STYLES[type];
  return ELEMENT_STYLES.note;
}

export function elementDimensions(type: ElementType): { width: number; height: number } {
  const s = styleForElementType(type);
  return { width: s.defaultWidth, height: s.defaultHeight };
}

export function defaultLabelForType(type: ElementType): string {
  return styleForElementType(type).label;
}

/** Resolve palette/canvas colors — custom cards use their stereotype definition. */
export function resolveElementStyle(
  element: Pick<StormElement, "type" | "metadata">,
  customCardTypes: CustomCardType[] = [],
): ElementStyle {
  const base = styleForElementType(element.type);
  if (element.type !== "customCard") return base;
  const def = findCustomCardType(customCardTypes, element.metadata?.customTypeId);
  if (!def) return base;
  return {
    ...base,
    label: def.name,
    shortLabel: stereotypeLabel(def.name),
    fill: def.fill,
    stroke: def.stroke,
    ink: def.ink,
  };
}

const SUBDOMAIN_KIND_CAPTION: Record<string, string> = {
  core: "Core",
  supporting: "Supporting",
  generic: "Generic",
};

/** Small type line shown at the top of a sticky. */
export function cardTypeCaption(
  element: Pick<StormElement, "type" | "metadata">,
  customCardTypes: CustomCardType[] = [],
): string {
  if (element.type === "aggregate") return "Aggregate Root";
  if (element.type === "subdomain") {
    const kind = element.metadata?.subdomainKind ?? "core";
    return `Subdomain · ${SUBDOMAIN_KIND_CAPTION[kind] ?? "Core"}`;
  }
  return resolveElementStyle(element, customCardTypes).label;
}

/** Style for a custom type row in the palette (before an element exists). */
export function styleForCustomCardType(def: CustomCardType): ElementStyle {
  const base = ELEMENT_STYLES.customCard;
  return {
    ...base,
    label: def.name,
    shortLabel: stereotypeLabel(def.name),
    fill: def.fill,
    stroke: def.stroke,
    ink: def.ink,
  };
}
