import type { ElementType } from "@/types/storm-element";

export interface ElementStyle {
  label: string;
  shortLabel: string;
  bg: string;
  border: string;
  text: string;
  /** Pastel hex for inline styles (palette / canvas). */
  fill: string;
  stroke: string;
  ink: string;
  defaultWidth: number;
  defaultHeight: number;
  shape: "rounded" | "rectangle" | "pill" | "wide";
  rotation?: number;
}

/** Soft post-it pastels — shared by palette buttons and canvas stickies. */
export const ELEMENT_STYLES: Record<ElementType, ElementStyle> = {
  domainEvent: {
    label: "Domain Event",
    shortLabel: "Event",
    bg: "bg-orange-100",
    border: "border-orange-300",
    text: "text-orange-950",
    fill: "#ffedd5",
    stroke: "#fdba74",
    ink: "#7c2d12",
    defaultWidth: 160,
    defaultHeight: 72,
    shape: "rounded",
  },
  command: {
    label: "Command",
    shortLabel: "Cmd",
    bg: "bg-blue-100",
    border: "border-blue-300",
    text: "text-blue-950",
    fill: "#dbeafe",
    stroke: "#93c5fd",
    ink: "#1e3a8a",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rounded",
  },
  actor: {
    label: "Actor",
    shortLabel: "Actor",
    bg: "bg-yellow-100",
    border: "border-yellow-300",
    text: "text-yellow-950",
    fill: "#fef9c3",
    stroke: "#fcd34d",
    ink: "#713f12",
    defaultWidth: 110,
    defaultHeight: 48,
    shape: "pill",
  },
  aggregate: {
    label: "Aggregate",
    shortLabel: "Agg",
    bg: "bg-yellow-100",
    border: "border-yellow-400",
    text: "text-yellow-950",
    fill: "#fef08a",
    stroke: "#facc15",
    ink: "#713f12",
    defaultWidth: 140,
    defaultHeight: 80,
    shape: "rectangle",
  },
  policy: {
    label: "Policy",
    shortLabel: "Policy",
    bg: "bg-fuchsia-100",
    border: "border-fuchsia-300",
    text: "text-fuchsia-950",
    fill: "#fae8ff",
    stroke: "#e879f9",
    ink: "#6b21a8",
    defaultWidth: 170,
    defaultHeight: 72,
    shape: "rounded",
  },
  readModel: {
    label: "Read Model",
    shortLabel: "Read",
    bg: "bg-emerald-100",
    border: "border-emerald-300",
    text: "text-emerald-950",
    fill: "#dcfce7",
    stroke: "#86efac",
    ink: "#064e3b",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rounded",
  },
  externalSystem: {
    label: "External System",
    shortLabel: "Ext",
    bg: "bg-pink-100",
    border: "border-pink-300",
    text: "text-pink-950",
    fill: "#fce7f3",
    stroke: "#f9a8d4",
    ink: "#9d174d",
    defaultWidth: 160,
    defaultHeight: 72,
    shape: "rectangle",
  },
  ui: {
    label: "UI",
    shortLabel: "UI",
    bg: "bg-slate-100",
    border: "border-slate-300",
    text: "text-slate-800",
    fill: "#f1f5f9",
    stroke: "#cbd5e1",
    ink: "#0f172a",
    defaultWidth: 130,
    defaultHeight: 60,
    shape: "rounded",
  },
  note: {
    label: "Notiz",
    shortLabel: "Notiz",
    bg: "bg-stone-50",
    border: "border-stone-300",
    text: "text-stone-800",
    fill: "#faf6ef",
    stroke: "#d6d0c4",
    ink: "#44403c",
    defaultWidth: 160,
    defaultHeight: 100,
    shape: "rounded",
  },
  hotspot: {
    label: "Hotspot",
    shortLabel: "Hot",
    bg: "bg-red-100",
    border: "border-red-300",
    text: "text-red-950",
    fill: "#fee2e2",
    stroke: "#fca5a5",
    ink: "#7f1d1d",
    defaultWidth: 120,
    defaultHeight: 120,
    shape: "rectangle",
    rotation: 45,
  },
  pivotalEvent: {
    label: "Pivotal Event",
    shortLabel: "Pivotal",
    bg: "bg-amber-100",
    border: "border-amber-300",
    text: "text-amber-950",
    fill: "#fef3c7",
    stroke: "#fcd34d",
    ink: "#7c2d12",
    defaultWidth: 280,
    defaultHeight: 48,
    shape: "wide",
  },
  entity: {
    label: "Entity",
    shortLabel: "Entity",
    bg: "bg-teal-100",
    border: "border-teal-300",
    text: "text-teal-950",
    fill: "#ccfbf1",
    stroke: "#5eead4",
    ink: "#134e4a",
    defaultWidth: 150,
    defaultHeight: 72,
    shape: "rounded",
  },
  valueObject: {
    label: "Value Object",
    shortLabel: "VO",
    bg: "bg-cyan-100",
    border: "border-cyan-300",
    text: "text-cyan-950",
    fill: "#cffafe",
    stroke: "#67e8f9",
    ink: "#164e63",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  domainService: {
    label: "Domain Service",
    shortLabel: "Service",
    bg: "bg-indigo-100",
    border: "border-indigo-300",
    text: "text-indigo-950",
    fill: "#e0e7ff",
    stroke: "#a5b4fc",
    ink: "#312e81",
    defaultWidth: 170,
    defaultHeight: 72,
    shape: "rounded",
  },
  repository: {
    label: "Repository",
    shortLabel: "Repo",
    bg: "bg-stone-100",
    border: "border-stone-400",
    text: "text-stone-900",
    fill: "#e7e5e4",
    stroke: "#a8a29e",
    ink: "#1c1917",
    defaultWidth: 150,
    defaultHeight: 68,
    shape: "rectangle",
  },
  factory: {
    label: "Factory",
    shortLabel: "Factory",
    bg: "bg-lime-100",
    border: "border-lime-300",
    text: "text-lime-950",
    fill: "#ecfccb",
    stroke: "#bef264",
    ink: "#365314",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  subdomain: {
    label: "Subdomain",
    shortLabel: "Sub",
    bg: "bg-violet-100",
    border: "border-violet-300",
    text: "text-violet-950",
    fill: "#ede9fe",
    stroke: "#c4b5fd",
    ink: "#4c1d95",
    defaultWidth: 200,
    defaultHeight: 88,
    shape: "rectangle",
  },
  rule: {
    label: "Rule",
    shortLabel: "Rule",
    bg: "bg-amber-100",
    border: "border-amber-400",
    text: "text-amber-950",
    fill: "#fde68a",
    stroke: "#fbbf24",
    ink: "#78350f",
    defaultWidth: 180,
    defaultHeight: 80,
    shape: "rounded",
  },
  example: {
    label: "Example",
    shortLabel: "Ex",
    bg: "bg-green-100",
    border: "border-green-300",
    text: "text-green-950",
    fill: "#bbf7d0",
    stroke: "#86efac",
    ink: "#14532d",
    defaultWidth: 170,
    defaultHeight: 90,
    shape: "rounded",
  },
  question: {
    label: "Question",
    shortLabel: "?",
    bg: "bg-sky-100",
    border: "border-sky-300",
    text: "text-sky-950",
    fill: "#bae6fd",
    stroke: "#7dd3fc",
    ink: "#0c4a6e",
    defaultWidth: 140,
    defaultHeight: 72,
    shape: "rounded",
  },
  activity: {
    label: "Activity",
    shortLabel: "Act",
    bg: "bg-blue-100",
    border: "border-blue-400",
    text: "text-blue-950",
    fill: "#bfdbfe",
    stroke: "#60a5fa",
    ink: "#1e3a8a",
    defaultWidth: 160,
    defaultHeight: 56,
    shape: "wide",
  },
  userTask: {
    label: "User Task",
    shortLabel: "Task",
    bg: "bg-sky-50",
    border: "border-sky-200",
    text: "text-sky-900",
    fill: "#e0f2fe",
    stroke: "#7dd3fc",
    ink: "#0c4a6e",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
  userStory: {
    label: "User Story",
    shortLabel: "Story",
    bg: "bg-yellow-50",
    border: "border-yellow-300",
    text: "text-yellow-950",
    fill: "#fef9c3",
    stroke: "#fde047",
    ink: "#713f12",
    defaultWidth: 160,
    defaultHeight: 88,
    shape: "rounded",
  },
  release: {
    label: "Release",
    shortLabel: "Rel",
    bg: "bg-rose-100",
    border: "border-rose-300",
    text: "text-rose-950",
    fill: "#fecdd3",
    stroke: "#fda4af",
    ink: "#881337",
    defaultWidth: 320,
    defaultHeight: 40,
    shape: "wide",
  },
  slice: {
    label: "Slice",
    shortLabel: "Slice",
    bg: "bg-orange-50",
    border: "border-orange-300",
    text: "text-orange-950",
    fill: "#ffedd5",
    stroke: "#fdba74",
    ink: "#7c2d12",
    defaultWidth: 220,
    defaultHeight: 48,
    shape: "wide",
  },
  processStart: {
    label: "Start",
    shortLabel: "Start",
    bg: "bg-emerald-100",
    border: "border-emerald-400",
    text: "text-emerald-950",
    fill: "#d1fae5",
    stroke: "#34d399",
    ink: "#064e3b",
    defaultWidth: 88,
    defaultHeight: 88,
    shape: "pill",
  },
  processEnd: {
    label: "Ende",
    shortLabel: "Ende",
    bg: "bg-slate-200",
    border: "border-slate-500",
    text: "text-slate-900",
    fill: "#e2e8f0",
    stroke: "#64748b",
    ink: "#0f172a",
    defaultWidth: 88,
    defaultHeight: 88,
    shape: "pill",
  },
  processActivity: {
    label: "Aktivität",
    shortLabel: "Schritt",
    bg: "bg-blue-100",
    border: "border-blue-300",
    text: "text-blue-950",
    fill: "#dbeafe",
    stroke: "#93c5fd",
    ink: "#1e3a8a",
    defaultWidth: 170,
    defaultHeight: 80,
    shape: "rounded",
  },
  processGateway: {
    label: "Gateway",
    shortLabel: "GW",
    bg: "bg-amber-100",
    border: "border-amber-400",
    text: "text-amber-950",
    fill: "#fef3c7",
    stroke: "#fbbf24",
    ink: "#78350f",
    defaultWidth: 100,
    defaultHeight: 100,
    shape: "rectangle",
  },
  dataEntity: {
    label: "Entität",
    shortLabel: "Entity",
    bg: "bg-cyan-100",
    border: "border-cyan-400",
    text: "text-cyan-950",
    fill: "#cffafe",
    stroke: "#22d3ee",
    ink: "#164e63",
    defaultWidth: 180,
    defaultHeight: 100,
    shape: "rectangle",
  },
  dataAssociation: {
    label: "Assoziation",
    shortLabel: "Assoz.",
    bg: "bg-violet-100",
    border: "border-violet-300",
    text: "text-violet-950",
    fill: "#ede9fe",
    stroke: "#c4b5fd",
    ink: "#4c1d95",
    defaultWidth: 140,
    defaultHeight: 64,
    shape: "rounded",
  },
};

export function elementDimensions(type: ElementType): { width: number; height: number } {
  const s = ELEMENT_STYLES[type];
  return { width: s.defaultWidth, height: s.defaultHeight };
}

export function defaultLabelForType(type: ElementType): string {
  return ELEMENT_STYLES[type].label;
}
